name: base_data
description: Flutter package for manage general repositories.
version: 0.0.1
repository: https://github.com/JoseTabares/base_data

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  base_models: ^0.0.2
  base_domain: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
