name: base_data
description: Flutter package for manage general repositories.
version: 2.0.0
repository: https://github.com/JoseTabares/base_data

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  base_models: ^2.0.0
  base_domain: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
